// <auto-generated />
using System;
using Epsilon.CodingSchool.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Epsilon.CodingSchool.EF.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20230215085839_RestrictComments")]
    partial class RestrictComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Epsilon.CodingSchool.Model.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TodoType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Finished");

                    b.ToTable("Todo", "App");
                });

            modelBuilder.Entity("Epsilon.CodingSchool.Model.TodoComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TodoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TodoId");

                    b.ToTable("TodoComment", "App");
                });

            modelBuilder.Entity("Epsilon.CodingSchool.Model.TodoDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TodoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TodoId")
                        .IsUnique();

                    b.ToTable("TodoDetail", "App");
                });

            modelBuilder.Entity("Epsilon.CodingSchool.Model.TodoComment", b =>
                {
                    b.HasOne("Epsilon.CodingSchool.Model.Todo", "Todo")
                        .WithMany("Comments")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("Epsilon.CodingSchool.Model.TodoDetail", b =>
                {
                    b.HasOne("Epsilon.CodingSchool.Model.Todo", "Todo")
                        .WithOne("Detail")
                        .HasForeignKey("Epsilon.CodingSchool.Model.TodoDetail", "TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("Epsilon.CodingSchool.Model.Todo", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Detail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
